window.PROJECT_DATA = {
  'city-park': {
    title: 'ЖК City Park',
    type: 'Apartment interiors',
    lead: 'Интерьер квартиры в классической спокойной палитре: спальня с мягкой текстильной зоной, компактная кухня, приватный санузел и гостиная с зелёным диваном как главным акцентом.',
    date: '09.2023',
    category: 'Apartment',
    area: '85 м²',
    rooms: '3',
    team: 'Евгения Лудупова',
    docs: 'Планировочное решение, рабочие чертежи, спецификации',
    visual: '3D renders',
    cover: 'assets/images/projects/city-park/render-19.jpg',
    fallback: 'assets/images/projects/city-park/cover.png',
    gallery: Array.from({ length: 22 }, (_, index) => `assets/images/projects/city-park/render-${String(index + 1).padStart(2, '0')}.jpg`),
  },
  vesna: {
    title: 'ЖК Весна',
    type: 'Apartment interiors',
    lead: 'Светлая квартира с мягкой кухонной зоной, тёплыми деревянными фактурами и спокойной планировкой для городской жизни.',
    date: '11.2025',
    category: 'Apartment',
    area: '82 м²',
    rooms: '3',
    team: 'Евгения Лудупова',
    docs: 'Планировочное решение, рабочие чертежи, спецификации',
    visual: '3D renders',
    cover: 'assets/images/projects/vesna/cover.png',
    fallback: 'assets/images/projects/vesna/cover.png',
    gallery: ['assets/images/projects/vesna/cover.png'],
  },
  mushu: {
    title: 'Кафе Мушу',
    type: 'Commercial interiors',
    lead: 'Атмосферное кафе с выразительным светом, графичными акцентами и камерной посадкой для вечернего формата.',
    date: '02.2024',
    category: 'Commercial',
    area: '120 м²',
    rooms: '1 зал',
    team: 'Евгения Лудупова',
    docs: 'Концепция, визуализация, подбор материалов',
    visual: '3D renders',
    cover: 'assets/images/projects/mushu/cover.png',
    fallback: 'assets/images/projects/mushu/cover.png',
    gallery: ['assets/images/projects/mushu/cover.png'],
  },
  'degre-apartment': {
    title: 'Degre Apartment',
    type: 'Apartment interiors',
    lead: 'Минималистичный интерьер с акцентом на свет, спокойные поверхности и чистые линии в деталях.',
    date: '2024',
    category: 'Apartment',
    area: '78 м²',
    rooms: '3',
    team: 'Евгения Лудупова',
    docs: 'Планировочное решение, рабочие чертежи',
    visual: '3D renders',
    cover: 'assets/images/projects/degre-apartment/cover.png',
    fallback: 'assets/images/projects/degre-apartment/cover.png',
    gallery: ['assets/images/projects/degre-apartment/cover.png'],
  },
  'degre-detail': {
    title: 'Interior Detail',
    type: 'Interior details',
    lead: 'Фрагменты интерьера, где материалы, свет и пропорции собирают характер проекта.',
    date: '2024',
    category: 'Detail',
    area: '-',
    rooms: '-',
    team: 'Евгения Лудупова',
    docs: 'Деталировка, материалы, спецификации',
    visual: '3D renders',
    cover: 'assets/images/projects/detail/cover.png',
    fallback: 'assets/images/projects/detail/cover.png',
    gallery: ['assets/images/projects/detail/cover.png'],
  },
};
