const selectedProjectImages = (project, numbers) =>
  numbers.map(number =>
    `assets/images/projects/${project}/web/${String(number).padStart(2, '0')}.jpg`
  );

window.PROJECT_DATA = {
  'city-park': {
    title: 'ЖК City Park',
    type: 'Apartment interiors',
    lead: 'Интерьер квартиры в классической спокойной палитре: спальня с мягкой текстильной зоной, компактная кухня, приватный санузел и гостиная с зелёным диваном как главным акцентом.',
    date: '09.2023',
    category: 'Apartment',
    area: '85 м²',
    rooms: '3',
    team: 'Евгения Лудупова',
    docs: 'Планировочное решение, рабочие чертежи, спецификации',
    visual: '3D renders',
    cover: 'assets/images/projects/city-park/web/08.jpg',
    fallback: 'assets/images/projects/city-park/web/08.jpg',
    plan: 'assets/images/projects/city-park/plan.png',
    gallery: selectedProjectImages('city-park', [8, 9, 1, 2, 5, 7, 10]),
  },
  vesna: {
    title: 'ЖК Весна',
    type: 'Apartment interiors',
    lead: 'Светлая квартира с мягкой кухонной зоной, тёплыми деревянными фактурами и спокойной планировкой для городской жизни.',
    date: '11.2025',
    category: 'Apartment',
    area: '82 м²',
    rooms: '3',
    team: 'Евгения Лудупова',
    docs: 'Планировочное решение, рабочие чертежи, спецификации',
    visual: '3D renders',
    cover: 'assets/images/projects/vesna/cover.jpg',
    fallback: 'assets/images/projects/vesna/cover.jpg',
    plan: 'assets/images/projects/vesna/plan.png',
    gallery: ['assets/images/projects/vesna/cover.jpg'],
  },
  mushu: {
    title: 'Кафе Мушу',
    type: 'Commercial interiors',
    lead: 'Атмосферное кафе с выразительным светом, графичными акцентами и камерной посадкой для вечернего формата.',
    date: '02.2024',
    category: 'Commercial',
    area: '120 м²',
    rooms: '1 зал',
    team: 'Евгения Лудупова',
    docs: 'Концепция, визуализация, подбор материалов',
    visual: '3D renders',
    cover: 'assets/images/projects/mushu/web/01.jpg',
    fallback: 'assets/images/projects/mushu/web/01.jpg',
    plan: 'assets/images/projects/mushu/plan.png',
    gallery: selectedProjectImages('mushu', [1, 2, 5, 6, 8, 10, 11, 13, 14, 15, 17, 18]),
  },
  smit: {
    title: 'ЖК SMIT',
    type: 'Apartment interiors',
    lead: 'Современный интерьер квартиры с мягкой природной палитрой, лаконичной мебелью и выразительными деталями.',
    date: '2024',
    category: 'Apartment',
    area: '—',
    rooms: '—',
    team: 'Евгения Лудупова',
    docs: 'Планировочное решение, рабочие чертежи, спецификации',
    visual: '3D renders',
    cover: 'assets/images/projects/smit/web/09.jpg',
    fallback: 'assets/images/projects/smit/web/09.jpg',
    plan: 'assets/images/projects/smit/plan.png',
    gallery: selectedProjectImages('smit', [9, 7, 11, 12, 16, 17, 3, 5, 13, 19, 1]),
  },
  'novo-ochakovo': {
    title: 'ЖК Новое Очаково',
    type: 'Apartment interiors',
    lead: 'Интерьер квартиры с продуманными сценариями света, спокойными оттенками и функциональными зонами для работы и отдыха.',
    date: '2025',
    category: 'Apartment',
    area: '—',
    rooms: '—',
    team: 'Евгения Лудупова',
    docs: 'Планировочное решение, рабочие чертежи, спецификации',
    visual: '3D renders',
    cover: 'assets/images/projects/novo-ochakovo/web/04.jpg',
    fallback: 'assets/images/projects/novo-ochakovo/web/04.jpg',
    plan: 'assets/images/projects/novo-ochakovo/plan.png',
    gallery: selectedProjectImages('novo-ochakovo', [4, 5, 7, 8, 9, 11, 13, 14, 15, 1]),
  },
  'georg-landrin': {
    title: 'ЖК Георг Ландрин',
    type: 'Apartment interiors',
    lead: 'Цельный интерьер квартиры, где тёплое дерево, деликатный цвет и графичные линии связывают все помещения.',
    date: '2023',
    category: 'Apartment',
    area: '—',
    rooms: '—',
    team: 'Евгения Лудупова',
    docs: 'Планировочное решение, рабочие чертежи, спецификации',
    visual: '3D renders',
    cover: 'assets/images/projects/georg-landrin/web/05.jpg',
    fallback: 'assets/images/projects/georg-landrin/web/05.jpg',
    plan: 'assets/images/projects/georg-landrin/plan.png',
    gallery: selectedProjectImages('georg-landrin', [5, 6, 1, 3, 4, 7]),
  },
  'dom-daryino': {
    title: 'Дом Дарьино',
    type: 'House interiors',
    lead: 'Интерьер загородного дома с просторными общими зонами, натуральными материалами и спокойной атмосферой.',
    date: '2024',
    category: 'House',
    area: '—',
    rooms: '—',
    team: 'Кожушаный Борис',
    docs: 'Планировочное решение, рабочие чертежи, спецификации',
    visual: '3D renders',
    cover: 'assets/images/projects/dom-daryino/web/02.jpg',
    fallback: 'assets/images/projects/dom-daryino/web/02.jpg',
    showPlan: false,
    gallery: selectedProjectImages('dom-daryino', [2, 1, 4, 5, 6, 7]),
  },
  talisman: {
    title: 'ЖК Талисман',
    type: 'Apartment interiors',
    lead: 'Светлая московская квартира с мягкой природной палитрой, зелёными акцентами и продуманным зонированием для повседневной жизни, работы и отдыха.',
    date: '07.2025',
    category: 'Apartment',
    area: '76,23 м²',
    rooms: '4',
    team: 'Евгения Лудупова · Вероника Никулова',
    docs: 'Планировочное решение, рабочие чертежи, спецификации',
    visual: '3D renders',
    cover: 'assets/images/projects/talisman/cover.jpg',
    fallback: 'assets/images/projects/talisman/web/05.jpg',
    plan: 'assets/images/projects/talisman/plan.png',
    planNote: 'Планировка объединяет отдельную кухню и гостиную с приватной частью квартиры. В ней предусмотрены спальня, кабинет, гардеробная, ванная и душевая, а также функциональная прихожая и лоджия.',
    gallery: selectedProjectImages('talisman', [5, 4, 3, 1, 2, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]),
  },
  '300-barista': {
    title: 'Триста Бариста',
    type: 'Commercial interiors',
    lead: 'Двухуровневая кофейня с открытой кухней, барной зоной и несколькими сценариями посадки. План рассчитан на 58 мест в основном зале и ещё 4 места у окон.',
    date: '—',
    category: 'Commercial',
    area: '81,7 м²',
    rooms: '2 этажа',
    team: 'Евгения Лудупова',
    docs: 'План расстановки мебели и оборудования',
    visual: 'Фотографии реализации',
    cover: 'assets/images/projects/300-barista/web/01.jpg',
    fallback: 'assets/images/projects/300-barista/web/01.jpg',
    plan: 'assets/images/projects/300-barista/plan.png',
    gallery: selectedProjectImages('300-barista', [1, 2, 3]),
  },
};
